name: Version Bump

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump version
        id: bump_version
        run: |
          # Read the current version from VERSION file
          current_version=$(cat VERSION)
          echo "Current version: $current_version"
          
          # Split the version into parts and increment the patch version
          IFS='.' read -r -a version_parts <<< "$current_version"
          version_parts[2]=$((version_parts[2] + 1))
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          echo "New version: $new_version"
          
          # Write the new version back to the VERSION file
          echo $new_version > VERSION

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add VERSION
          git commit -m "chore(release): bump version to $new_version"
          git tag "v$new_version"
          git push origin HEAD --follow-tags
